### ISSUE TITLE
Kentico.Xperience.Libraries dependency in the admin app

### ISSUE THREAD

**Issue by phixxo** [Kentico/xperience-twilio-sendgrid#9]
Installing the Nuget package will also install the Kentico.Xperience.Libraries package to the admin app which can cause various issues. Moreover, the CMSApp is set to use DLLs from the LIB folder, so whatever is brought to the app by the package, can be overridden after building the project. Also, users must be really careful on the hotfix versions applied, package versions installed, etc. It does not sound like a good practice.

**Comment by abao168899** [comment]
乡村振兴147万扶贫金免费办理，年前最后一批补贴，火速加老师微信: 17054264532 【国家系统app放发，时效有限免费领取，让你缴纳费用都是骗子，尽快与相关部门联系领取

**Comment by Sapphirress** [comment]
Closing with an explanation from Sean: https://github.com/Kentico/xperience-twilio-sms/issues/4
